# coding: utf-8

"""
    Exact Online Rest API

    Interact with Exact Online database

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_division_logistics_item_groups_get(self):
        """
        Test case for division_logistics_item_groups_get

        
        """
        pass

    def test_division_logistics_items_get(self):
        """
        Test case for division_logistics_items_get

        Gets a list of items
        """
        pass

    def test_division_logistics_items_guiditem_id_delete(self):
        """
        Test case for division_logistics_items_guiditem_id_delete

        Delete an item from the database
        """
        pass

    def test_division_logistics_items_guiditem_id_put(self):
        """
        Test case for division_logistics_items_guiditem_id_put

        Update an item in the database
        """
        pass

    def test_division_logistics_items_post(self):
        """
        Test case for division_logistics_items_post

        Add a new item to the database
        """
        pass

    def test_division_manufacturing_time_transactions_get(self):
        """
        Test case for division_manufacturing_time_transactions_get

        
        """
        pass

    def test_division_manufacturing_time_transactions_post(self):
        """
        Test case for division_manufacturing_time_transactions_post

        
        """
        pass

    def test_get_me(self):
        """
        Test case for get_me

        Get the current user's account information
        """
        pass


if __name__ == '__main__':
    unittest.main()
