# coding: utf-8

"""
    Exact Online Rest API

    Interact with Exact Online database

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class ShopOrder(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, description=None, shop_order_number=None):
        """
        ShopOrder - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'description': 'str',
            'shop_order_number': 'str'
        }

        self.attribute_map = {
            'id': 'ID',
            'description': 'Description',
            'shop_order_number': 'ShopOrderNumber'
        }

        self._id = id
        self._description = description
        self._shop_order_number = shop_order_number

    @property
    def id(self):
        """
        Gets the id of this ShopOrder.


        :return: The id of this ShopOrder.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ShopOrder.


        :param id: The id of this ShopOrder.
        :type: str
        """

        self._id = id

    @property
    def description(self):
        """
        Gets the description of this ShopOrder.


        :return: The description of this ShopOrder.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this ShopOrder.


        :param description: The description of this ShopOrder.
        :type: str
        """

        self._description = description

    @property
    def shop_order_number(self):
        """
        Gets the shop_order_number of this ShopOrder.


        :return: The shop_order_number of this ShopOrder.
        :rtype: str
        """
        return self._shop_order_number

    @shop_order_number.setter
    def shop_order_number(self, shop_order_number):
        """
        Sets the shop_order_number of this ShopOrder.


        :param shop_order_number: The shop_order_number of this ShopOrder.
        :type: str
        """

        self._shop_order_number = shop_order_number

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
